
/**
* TchatClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TchatSC.idl
* vendredi 3 mai 2013 17 h 36 CEST
*/

public final class TchatClientHolder implements org.omg.CORBA.portable.Streamable
{
  public TchatClient value = null;

  public TchatClientHolder ()
  {
  }

  public TchatClientHolder (TchatClient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TchatClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TchatClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TchatClientHelper.type ();
  }

}
