
/**
* TchatServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TchatSC.idl
* vendredi 3 mai 2013 17 h 36 CEST
*/

abstract public class TchatServerHelper
{
  private static String  _id = "IDL:TchatServer:1.0";

  public static void insert (org.omg.CORBA.Any a, TchatServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TchatServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TchatServerHelper.id (), "TchatServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TchatServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TchatServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TchatServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TchatServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TchatServer)
      return (TchatServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _TchatServerStub stub = new _TchatServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TchatServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TchatServer)
      return (TchatServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _TchatServerStub stub = new _TchatServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
