
/**
* TchatClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TchatSC.idl
* vendredi 3 mai 2013 17 h 36 CEST
*/

public interface TchatClientOperations 
{
  void connect (String srv);
  void send (String msg);
  void receive (String msg);
} // interface TchatClientOperations
