
/**
* TchatServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TchatSC.idl
* vendredi 3 mai 2013 17 h 36 CEST
*/

public abstract class TchatServerPOA extends org.omg.PortableServer.Servant
 implements TchatServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("register", new java.lang.Integer (0));
    _methods.put ("dispatch", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TchatServer/register
       {
         TchatClient c = TchatClientHelper.read (in);
         this.register (c);
         out = $rh.createReply();
         break;
       }

       case 1:  // TchatServer/dispatch
       {
         String msg = in.read_string ();
         this.dispatch (msg);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TchatServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public TchatServer _this() 
  {
    return TchatServerHelper.narrow(
    super._this_object());
  }

  public TchatServer _this(org.omg.CORBA.ORB orb) 
  {
    return TchatServerHelper.narrow(
    super._this_object(orb));
  }


} // class TchatServerPOA
