
/**
* TchatServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TchatSC.idl
* vendredi 3 mai 2013 17 h 36 CEST
*/

public final class TchatServerHolder implements org.omg.CORBA.portable.Streamable
{
  public TchatServer value = null;

  public TchatServerHolder ()
  {
  }

  public TchatServerHolder (TchatServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TchatServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TchatServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TchatServerHelper.type ();
  }

}
