
/**
* TchatClientPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TchatSC.idl
* vendredi 3 mai 2013 17 h 36 CEST
*/

public abstract class TchatClientPOA extends org.omg.PortableServer.Servant
 implements TchatClientOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("connect", new java.lang.Integer (0));
    _methods.put ("send", new java.lang.Integer (1));
    _methods.put ("receive", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TchatClient/connect
       {
         String srv = in.read_string ();
         this.connect (srv);
         out = $rh.createReply();
         break;
       }

       case 1:  // TchatClient/send
       {
         String msg = in.read_string ();
         this.send (msg);
         out = $rh.createReply();
         break;
       }

       case 2:  // TchatClient/receive
       {
         String msg = in.read_string ();
         this.receive (msg);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TchatClient:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public TchatClient _this() 
  {
    return TchatClientHelper.narrow(
    super._this_object());
  }

  public TchatClient _this(org.omg.CORBA.ORB orb) 
  {
    return TchatClientHelper.narrow(
    super._this_object(orb));
  }


} // class TchatClientPOA
