
/**
* TchatServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TchatSC.idl
* vendredi 3 mai 2013 17 h 36 CEST
*/

public interface TchatServerOperations 
{
  void register (TchatClient c);
  void dispatch (String msg);
} // interface TchatServerOperations
